### ISSUE TITLE
Clownfish and Pufferfish create broken textures when smelted.

### ISSUE THREAD

**Issue by JamieSinn** [LeVipah/Smelter#1]
http://www.ecocitycraft.com/forum/threads/bug-report-broken-fishies.126159/

> Minecraft Username:
> Avowin
> Brief Description:
> Accidentally /smelt'd clownfish and puffer fish, and they became broken textured
> Instructions:
> Obtain one of these fishes
> /smelt (or /smeltall)
> becomes broken textured
> How many times did you recreate this bug?: twice
> 
> Result: broken textured block
> 
> Expected Result: No change
> 
> Evidence:

**Comment by LeVipah** [comment]
Thanks for your PR, I have merged it.
